// Copyright 2019, Oath Inc.
// Licensed under the terms of the Apache 2.0 license. See LICENSE file in the root of the distribution for licensing details.
#include <string>
#include <fstream>
#include <sys/stat.h>

#include "common.h"
#include "TestHMConfigParserBase.h"
#include "HMStateManager.h"

using namespace std;

CPPUNIT_TEST_SUITE_REGISTRATION(TESTNAME);

void TESTNAME::setUp()
{
    setupCommon();
    mkdir("./dir1", S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
    mkdir("./dir1/dir2", S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);

    ofstream fout("./dir1/dir2/testdir.yaml");
    fout << "-   name: test1.netchasm.com" << endl;
    fout.close();
}

void TESTNAME::tearDown()
{
    teardownCommon();
    remove("./dir1/dir2/testdir.yaml");
    remove("./dir1/dir2");
    remove("./dir1");
}

void TESTNAME::test_parseDirectory()
{
    TestConfigParser parser;
    string path = "garbage";
    HMState state;
    CPPUNIT_ASSERT_EQUAL(1, (int)HMConfigParserBase::parseDirectory(path,  state));
    
    path =
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbag"
      "e/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
            "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbag"
      "e/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
            "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbag"
      "e/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
            "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbag"
      "e/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
            "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/"
      "garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbag"
      "e/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage/garbage"
      "/garbage/garbage/garbagegarbagegarbage";
    CPPUNIT_ASSERT_EQUAL(1, (int)HMConfigParserBase::parseDirectory(path, state));
      
    path = "./dir1";
    CPPUNIT_ASSERT_EQUAL(0, (int)HMConfigParserBase::parseDirectory(path, state));

    path = "./dir1/dir2";
    CPPUNIT_ASSERT_EQUAL(0, (int)HMConfigParserBase::parseDirectory(path, state));
}
